name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: |
          echo "Hello ${{ inputs.who-to-greet }}"
          echo "Said Hello To ${{ inputs.who-to-greet }}" >> $GITHUB_STEP_SUMMARY
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT    
