name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow-1:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: '@22367rh'

  call-workflow-2:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: 'World'

  call-workflow-3:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: 'Universe'

  use-outputs:
    runs-on: ubuntu-latest
    needs: [call-workflow-1, call-workflow-2, call-workflow-3]
    steps:
      - run: echo "Time 1 was ${{ needs.call-workflow-1.outputs.current-time }}"
      - run: echo "Time 2 was ${{ needs.call-workflow-2.outputs.current-time }}"
      - run: echo "Time 3 was ${{ needs.call-workflow-3.outputs.current-time }}"
      - run: |
          echo "Workflow 1 Time was ${{ needs.call-workflow-1.outputs.current-time }}" >> $GITHUB_STEP_SUMMARY
          echo "Workflow 2 Time was ${{ needs.call-workflow-2.outputs.current-time }}" >> $GITHUB_STEP_SUMMARY
          echo "Workflow 2 Time was ${{ needs.call-workflow-3.outputs.current-time }}" >> $GITHUB_STEP_SUMMARY
