name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow-1:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: '@22367rh'

  call-workflow-2:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: 'World'

  call-workflow-3:
    uses: ./.github/workflows/reuasable.yml
    with:
      who-to-greet: 'Universe'

  use-output-1:
    runs-on: ubuntu-latest
    needs: [call-workflow-1]
    steps:
      - run: echo "Time was ${{ needs.call-workflow-1.outputs.current-time }}"
      
  use-output-2:
    runs-on: ubuntu-latest
    needs: [call-workflow-2]
    steps:
      - run: echo "Time was ${{ needs.call-workflow-2.outputs.current-time }}"
      
  use-output-3:
    runs-on: ubuntu-latest
    needs: [call-workflow-3]
    steps:
      - run: echo "Time was ${{ needs.call-workflow-3.outputs.current-time }}"
